apiVersion: apps/v1
kind: Deployment
metadata:
  name: team4-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team4app
  template:
    metadata:
      labels:
        app: team4app
    spec:
      containers:
        - name: team4-container
          image: team4/team4html
          imagePullPolicy: Always
          ports:
            - containerPort: 3000